spring:
  profiles:
    name: octoevents
    active: prod
  datasource:
    url: jdbc:postgresql://db:5432/test
    username: postgres
    password: octoevents42

server:
  port: 8080
logging:
  file: /var/log/octoevents.log
  level: INFO

